version: '3.7'
services:
#****************************************  backend********************************************************
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      # HOST:CONTAINER
      - "3000:3000"
    restart: on-failure
    depends_on:
      - db
#****************************************  frontend ********************************************************
  frontend:
    build: ./frontend
    ports:
      - "7070:7070"
    restart: on-failure
    depends_on:
      - backend
#********************************************  database ****************************************************
  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    restart: on-failure
    ports:
      # HOST:CONTAINER
      - 5432:5432
